### ISSUE TITLE
install dependent packages line not working

### ISSUE THREAD

**Issue by beatonan** [dustming/basinmaker#11]
There appears to be a minor error in the "install dependent packages" line on the installation instructions website (https://basinmaker.readthedocs.io/en/latest/installation.html#light-installation).  Very minor but i did not realize this line did not work and had errors later in the installation process that I had to trace back to this issue.

python **- m** pip install pandas pytest scipy simpledbf netCDF4 jupyter

should be 

python **-m** pip install pandas pytest scipy simpledbf netCDF4 jupyter

**Comment by dustming** [comment]
Thanks for your feedback, the topo is corrected.
