### ISSUE TITLE
Generate_HRUs cannot add the field a_HRULake_ID

### ISSUE THREAD

**Issue by Scriptbash** [dustming/basinmaker#12]
When running the Generate_HRUs function, it says it cannot add the field "a_HRULake_ID". I think it may be because the field name is longer than 10 characters, but it may be something else too.
Here are the messages from the script:

ERROR 6: Failed to add field named 'a_HRULake_ID'
ERROR: Unable to create column <a_HRULake_ID>
Module run None v.out.ogr --o input=union_1 output=/root/BasinMaker/OIH_Output/network_after_filter_lakes/union_1_.shp format=ESRI_Shapefile ended with error
Process ended with non-zero return code 1. See errors in the (error) output.

The version of BasinMaker is 2.2.6. Let me know if I forgot important info!

**Comment by dustming** [comment]
Hi, I agree with what you said. Would you please include your inputs and the script here? Or send it to m43han@uwaterloo.ca?

**Comment by dustming** [comment]
Solved in master version
