### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Jhydromet** [dustming/basinmaker#13]
Might not be a great issue for github here, but I've failed on installation for full version of BasinMaker.

Worked through the installation procedure on https://basinmaker.readthedocs.io/en/latest/installation.html for full installation. 

Everything went smooth, the only subtle difference I encountered was that my python installation location was in:

C:\OSGeo4W\bin\python.exe

and not in:

C:\OSGeo4W\apps\Python37\python.exe

as described in the documentation.

This was what I encountered upon attempting installation test:

C:\Temp\test>python test_full_installation.py
PyTables is not installed. No support for HDF output.
SQLalchemy is not installed. No support for SQL output.
Mask Region:   Using provided DEM :
Logged warning: Duplicate provider native registered
[WinError 5] Access is denied
 please report error message to m43han@uwaterloo.ca or create an issue in https://github.com/dustming/basinmaker/issues

Cheers,
Jeremy

**Comment by dustming** [comment]
Hi @Jhydromet  
    
   Sorry to hear that. 
   Did you install the latest "QGIS in OSGeo4W (recommended for regular users):" in https://qgis.org/en/site/forusers/download.html here?  The Python installed here should be Python39.  Would you please help me check the following things 

-    check if "C:\OSGeo4W\bin\python.exe" also exists in the folder?
-    check if the following libraries can be loaded without error 

![image](https://user-images.githubusercontent.com/40034156/176235053-ce486df2-e41b-4757-8c93-a183b93c22c3.png)

-    The error message seems like a permission issue.  Would you please run "basinmaker.bat" as administrator and move the test folder to a path without "space" in it. And see if the error message is still there. 

Thanks 
Ming

**Comment by dustming** [comment]
No response recieved
