### ISSUE TITLE
Grass 82 error

### ISSUE THREAD

**Issue by Scriptbash** [dustming/basinmaker#16]
Hi Ming,

Using GRASS 8.2.1 (current latest version) gives an error message when trying to delineate a watershed from a DEM. 
Here are the error messages:

Cannot create: /root/BasinMaker/bm_tmp/grassdb/main_working_location/PERMANENT with the following options: . Executing:
grass -c  -e /root/BasinMaker/bm_tmp/grassdb/main_working_location/PERMANENT
GRASS said:
"Starting GRASS GIS...\nERROR: Mapset </root/BasinMaker/bm_tmp/grassdb/main_working_location/PERMANENT> already exists.\nExiting..."

Even if I delete the "bm_tmp" folder, the error comes back. I think it happens since GRASS 8.0, but I'm not 100% sure. The BasinMaker version is 3.0.3. Let me know if you need more details!

**Comment by dustming** [comment]
Hi @Scriptbash, I will test it in next week—many thanks for sharing the error message.

**Comment by dustming** [comment]
Hi @Scriptbash , I tried to install grass 82 via OSGEO4W and test basinmaker with GRASS82, but it requires more time than I expected.  Is it possible for us to stay with GRASS 78 for now?

**Comment by dustming** [comment]
Worked with GRASS78, we will test GRASS8 Later
