### ISSUE TITLE
HRU ID 0 in shapefile but not rvh

### ISSUE THREAD

**Issue by rchlumsk** [dustming/basinmaker#8]
The hru shapefiles (final_cat_hru) appears to be generated with an hru of ID zero (0). However, this element is not written to the rvh file. Since Raven requires all subbasin and HRU IDs to be positive integers (i.e. >0), ideally the shapefile generation assigns all positive integer IDs to avoid this issue.

**Comment by dustming** [comment]
Thanks, rob, fixed.
